### ISSUE TITLE
Allow offline installation with Connect

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#17]
##### SUMMARY

Some times the execution of the playbook can happen in an air-gapped or disconnected environment, so downloading artifacts is not available. It could be nice to have an option to allow the installation of the Kafka ecosystem using local copies of the artifacts.

This feature can be identified with a boolean variable like `amq_streams_offline_install` to enable it. Also a property like `amq_streams_archive` can identify the pattern of the file to upload into the final hosts.

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
That should be covered by [PR26](https://github.com/ansible-middleware/amq_streams/pull/26). 

To prevent Ansible to download the file from the website, you set the amq_streams_common_offline_install var to True:

`$ ansible-playbook -e amq_streams_common_offline_install=True...`

(or in the vars of the playbook)

By default, the collection expects the archive file to be: `/opt/kafka_2.13-3.3.2.tgz` (on the control node), but this can be override (as usual).

**Comment by rmarting** [comment]
@rpelisse Tested successfully from the current status of the `main` branch. I created the PR #27 to improve the documentation about this stuff.

If you agree with the content of the PR, after merging into the main branch, this issue can be closed.

HTH

**Comment by rpelisse** [comment]
Let me catch up (and merge all your PR and add the fix I want to add). Can you describe me a bit more your issue? You can't install Connect offline, right?

**Comment by rmarting** [comment]
Yes, I can't! The playbook wants to download the binary artifact instead of use the package located in the folder identified.

this only happens with the kafka connect. Zookeeper and broker work successfully.

**Comment by rpelisse** [comment]
Damn playbook! They really have a will of their own, haven't they! :)

Noted, I'll take a look asap.

**Comment by rpelisse** [comment]
@rmarting As you mentioned on #47 that it worked for you, I'm closing this issue. Feel free to reopen if I misunderstood something!
