### ISSUE TITLE
Define a distributable deployment topology

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#22]
##### SUMMARY

The current status of the playbook uses the same host to install all the components of the Kafka ecosystem (zookeeper, broker, and kafka connect instances), however, it is very common that each component is deployed in a different set of hosts. This is a common pattern to improve the performance and avoid resource consuption conflits.

The idea should be to define a host family for each component in the inventory, something similar to:

```
[zookeeper]
zkserver01
zkserver02
zkserver03

[broker]
bkserver01
bkserver02
bkserver03

[kconnect]
kcserver01
kcserver02
kcserver03
```

Each role must executed for the specific host groups in a map similar to:

* `[zookeeper]` hosts will execute the `amq_streams_common` and `amq_streams_koopeeper` roles
* `[broker]` hosts will execute the `amq_streams_common` and `amq_streams_broker` roles
* `[kconnect]` hosts will execute the `amq_streams_common` and `amq_streams_connect` roles

This feature is similar to the feature request #7, as some of the properties/values must be defined per hosts.

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
That's provided by Ansible feature. The playbook is not designed to be used as is production environment, but just a quick to setup all the amq_streams component. 

In "real world", each component will have its own playbook bound to its own set of hosts (so the 'connect' playbooks with have `hosts: kconnect` and only execute the `amq_streams_connect` role.

AFAIK, there is no refactor to be done, I've tried this approach a few ago (with a VM for each component) and it worked.

Did you see a missing props or stumble upon some issue?

**Comment by rmarting** [comment]
Got it @rpelisse !!! It makes sense to create specific playbooks to manage each component of the Kafka ecosystem. I am missing documentation about that usage and provide some patterns on top of these decissions. 

Let me add some content about how to use this collection in a proper way.

**Comment by rmarting** [comment]
Added some references in the #23 describing how to use the collection with different patterns. HTH
