### ISSUE TITLE
AMQ Streams documentation site is not rendering the styles

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#25]
##### SUMMARY

The status of the Document site at [https://ansiblemiddleware.com/amq_streams/](https://ansiblemiddleware.com/amq_streams/) is:

![image](https://github.com/ansible-middleware/amq_streams/assets/8723668/5c1b80b6-f605-418b-95be-142a3485135a)

Any references to the style resources (js, css, images) are returning 404 (not found) exceptions, so the site is not usable to review the documentation.

##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

Browser the documentation site at [https://ansiblemiddleware.com/amq_streams/](https://ansiblemiddleware.com/amq_streams/) 

##### EXPECTED RESULTS

Same user experience as the other middleware collection sites.

**Comment by guidograzioli** [comment]
Fixed by adding `.nojekill` to gh-pages branch
