### ISSUE TITLE
Define the right folders for ZK logs and BK data

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#29]
##### SUMMARY

ZK and BK manages two different concepts to manage the data of each component. ZK uses a _logs_ folder to store the transaction log of the in-memory database, however, BK uses a _logs_ folder to store the commit logs (at the end the segments where the messages are stored. So, here the concept of _log_ is not related to the usual concept of logs to track the behaviour of a process.

As the ZK and BK both manages outputs (logs) as process running on a system, these folders should be different from the original defines to store data.

The current definition of the roles are not using the right folders and use cases for the data of each component.

**ZK configuration**:

`dataDir` is the directory to store ZK transaction log and snapshots of the in-memory database. It is not the "log" of a service. This value usually is defined in the `/var/lib/zookeeper/` folder. This property is declared in the `zookeeper.properties` file.

References: 
* https://access.redhat.com/documentation/en-us/red_hat_amq_streams/2.4/html-single/using_amq_streams_on_rhel/index#proc-running-single-node-amq-streams-cluster-str

**BK configuration**:

`log.dirs` is the directory to store commit logs in one or multiple log files. It means that it is the data of the brokers, not the logs of the service. This property is usually defined with the value `/var/lib/kafka` in the `server.properties` file.

References:
* https://kafka.apache.org/32/documentation.html#brokerconfigs_log.dir
* https://access.redhat.com/documentation/en-us/red_hat_amq_streams/2.4/html-single/using_amq_streams_on_rhel/index#con-kafka-commit-log-configuration-str

##### ISSUE TYPE
 - Feature Idea

**Comment by rmarting** [comment]
@guidograzioli Should we close this issue as the PR was merged?

**Comment by guidograzioli** [comment]
yup
