### ISSUE TITLE
Set up KAFKA environment variables for the service execution

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#53]
##### SUMMARY

Kafka declares the following environment variables in the `kafka-run-class.sh` file to customize the JVM, GC, JMX and logging capabilities of the processes:

* `$KAFKA_HEAP_OPTS` -> Already included in the collection by the `amq_streams_broker_java_heap_opts`
* `$KAFKA_JVM_PERFORMANCE_OPTS`
* `$KAFKA_GC_LOG_OPTS`
* `$KAFKA_JMX_OPTS`
* `$KAFKA_LOG4J_OPTS`

It could be great allow to set up these variables in the service unit definition in the same way is doing for the `KAFKA_HEAP_OPTS`.

These variables can be declared without any default values, as the `kafka-run-class.sh` file declares in that case the default values. However the roles should allow to declare these values.

These properties applies for zookeepeer and broker both, so the implementation and way of configuration can be similar or equals.

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
Good idea!

We already have a few of those in the systemd's config file template:

- $KAFKA_HEAP_OPTS :heavy_check_mark: 
- $KAFKA_LOG4J_OPTS :heavy_check_mark: 

So I'll add the following ones:
- $KAFKA_JVM_PERFORMANCE_OPTS
- $KAFKA_GC_LOG_OPTS
- $KAFKA_JMX_OPTS

However, we may need to provide component specific vars (ex: amq_streams_connect_kafka_jmx_opts to define the value for all the instances of connect).  WDTY?

**Comment by rpelisse** [comment]
Fixed by #54

**Comment by rmarting** [comment]
Complemented by #55 with the documentation of the implentation of #54.
