### ISSUE TITLE
Validate the odd number of Zookeeper instances of the cluster

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#6]
##### SUMMARY

Zookeeper is a distributed system based in a quorum-mechanism to verify and store the information, that it means that the number of instances of the assemble must be an odd number (1 - minimum , [3|5] - the most common, 7 - for large clusters).

The ansible playbook should check that we are managing a well-formed Zookeeper cluster.

Reference:
- https://kafka.apache.org/33/documentation.html#zk

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
@rmarting Can you review the PR? Let me know if you have feedback about it?

Thanks ! :)
