### ISSUE TITLE
Support for TLS encryption for Kafka Brokers

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#63]
##### SUMMARY

Kafka brokers support TLS encryption for communication with Kafka clients. The `amq_streams_broker` role should provide the capability to declare a SSL listener using the right private and publich keys stored in a keystore. The keystore should be also managed by the role to copy in each Kafka broker managed by the collection.

References:

* [AMQ Streams - TLS Encryption](https://access.redhat.com/documentation/en-us/red_hat_amq_streams/2.4/html-single/using_amq_streams_on_rhel/index#con-kafka-tls-encryption-str)

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
@rmarting is it something you feel you could implement?

**Comment by rmarting** [comment]
Challenge accepted!!!
![image](https://github.com/ansible-middleware/amq_streams/assets/8723668/9305e812-9d36-44b1-a0f2-1c08438b3d51)

**Comment by Neustradamus** [comment]
@rmarting: Good job about SCRAM!

Linked to:
- https://github.com/scram-sasl/info/issues/1
- https://github.com/ansible-middleware/amq_streams/issues/63
- https://github.com/ansible-middleware/amq_streams/pull/70
- https://github.com/ansible-middleware/amq_streams/pull/73
- https://github.com/ansible-middleware/amq_streams/pull/74
- https://github.com/ansible-middleware/amq_streams/pull/76
