### ISSUE TITLE
Use an specific role for each main component of an Apache Kafka cluster

### ISSUE THREAD

**Issue by rmarting** [ansible-middleware/amq_streams#8]
##### SUMMARY

An Apache Kafka cluster contains the following main components:

* A Zookeeper ensemble (for now, as at some point Zookeeper will be removed)
* A Kafka broker cluster

It could be usefull to split the current collection into 2 different roles:

* roles/zookeeper: To centralize all the tasks to install, deploy, and operate the Zookeper ensemble
* roles/kafka: To centralize all the tasks to install, deploy, and operate the Kafka cluster

This approach could help to mantain better each member of the ecosystem, and not add all the tasks in the same place. In the future, as soon Zookeeper is removing and others components (Kraft) are including, then new roles can play a better maintanibility.

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
It was more/less on my TODO list. However, there is a lot of code duplication if we do that, so we probably need to have 3 roles amq_stream, amq_streams_zookeeper and amq_streams_commons.

**Comment by rmarting** [comment]
Indeed! Commons, Zookeeper, and Kafka roles are a better approach.

**Comment by rpelisse** [comment]
Note that we do need to use amq_streams in front and I'm not sure about using Kafka (for © reason).

**Comment by rmarting** [comment]
The new structure of the collection, using multiple roles especialized to cover different components, is aligned with this issue. IMHO we can close it. What do you think?

@rpelisse :point_up:

**Comment by rpelisse** [comment]
You are right! Thanks for pointing this out!
