### ISSUE TITLE
Support for ADVERTISE LISTENERS

### ISSUE THREAD

**Issue by hodrigohamalho** [ansible-middleware/amq_streams#84]
##### SUMMARY
It's a common use case to set advertise listeners for external access in the Kafka cluster, as explained in the image below:
![External_Listener_Internal_Listener-e1561748465911](https://github.com/ansible-middleware/amq_streams/assets/252998/07d28f62-07d9-438d-85d3-12157bfab56d)

This request is to add the support of advertise_listener in the playbook, so we will be able to set internal/external IPs during the provisioning. 

Best regards

##### ISSUE TYPE
 - Feature Idea

**Comment by rpelisse** [comment]
@rmarting WDYT about this feature proposal?

**Comment by rmarting** [comment]
It is one of the capabilities of Kafka to expose the endpoints. So, it makes sense to allow to define in the collection. It should not be complex to implement, as it is very similar to the broker listeners (`amq_streams_broker_listeners`) that we have already implemented.

**Comment by rmarting** [comment]
@hodrigohamalho If you want to test it, the implementation was merged and ready for its use!
